In [1]:
from google.colab import auth
from google.cloud import bigquery
import pandas as pd

auth.authenticate_user()
project_id = "gold-yen-408708" # Ini project ID
client = bigquery.Client(project=project_id)

In [2]:
query = """SELECT
	A.YEAR,
	A.MONTH,
	COUNT(A.MONTH) AS TOTAL_PATENT
FROM
	(SELECT
		EXTRACT(YEAR FROM (PARSE_DATE('%Y%m%d', Filing_Date))) AS YEAR,
		EXTRACT(MONTH FROM (PARSE_DATE('%Y%m%d', Filing_Date))) AS MONTH
	FROM patents-public-data.uspto_oce_cancer.publications
	WHERE
		EXTRACT(YEAR FROM (PARSE_DATE('%Y%m%d', Filing_Date))) BETWEEN 2012 AND 2023) AS A
GROUP BY
	A.YEAR, A.MONTH
ORDER BY
	A.YEAR DESC,
	A.MONTH ASC;"""
# Set up the query

query_job = client.query(query).to_dataframe()
query_job

    YEAR  MONTH  TOTAL_PATENT
0   2016      1           344
1   2016      2           253
2   2016      3           214
3   2016      4            46
4   2015      1           540
5   2015      2           576
6   2015      3           600
7   2015      4           560
8   2015      5           492
9   2015      6           614
10  2015      7           625
11  2015      8           521
12  2015      9           570
13  2015     10           457
14  2015     11           425
15  2015     12           459
16  2014      1          1006
17  2014      2          1045
18  2014      3          1865
19  2014      4          1086
20  2014      5          1005
21  2014      6           960
22  2014      7          1015
23  2014      8           815
24  2014      9           716
25  2014     10           686
26  2014     11           612
27  2014     12           733
28  2013      1          1061
29  2013      2          1164
30  2013      3          2223
31  2013      4           980
32  2013      5          1274
33  2013      6          1098
34  2013      7          1221
35  2013      8          1124
36  2013      9          1148
37  2013     10          1223
38  2013     11          1145
39  2013     12          1276
40  2012      1          1181
41  2012      2          1198
42  2012      3          1515
43  2012      4          1358
44  2012      5          1418
45  2012      6          1391
46  2012      7          1255
47  2012      8          1306
48  2012      9          1455
49  2012     10          1289
50  2012     11          1244
51  2012     12          1302